#!/bin/env sh

lock() {
  i3lock-fancy $@
}

action="$1"
shift

case $action in
  lock)
    lock $@
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    lock $@ && systemctl suspend
    ;;
  hibernate)
    lock $@ && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl shutdown
    ;;
  *)
    echo "Usage: $0 {}"
    exit 2
    ;;
esac

exit 0
